version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
  db:
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: